master:
  web_trigger_all:
    - services:
        - docker
      docker:
        image: cnbcool/default-build-env:latest
        volumes:
          - /root/
      stages:
        - name: docker login
          script:
            - docker login -u ${CNB_TOKEN_USER_NAME} -p "${CNB_TOKEN}" ${CNB_DOCKER_REGISTRY}

        - name: 构建:nodejs24
          script:
            - cd ./nodejs/24
            - docker build -t ${CNB_DOCKER_REGISTRY}/php127/docker/nodejs:24-alpine .
            - docker push ${CNB_DOCKER_REGISTRY}/php127/docker/nodejs:24-alpine

        - name: 构建:nodejs22
          script:
            - cd ./nodejs/22
            - docker build -t ${CNB_DOCKER_REGISTRY}/php127/docker/nodejs:22-alpine .
            - docker push ${CNB_DOCKER_REGISTRY}/php127/docker/nodejs:22-alpine

        - name: 构建:nodejs20
          script:
            - cd ./nodejs/20
            - docker build -t ${CNB_DOCKER_REGISTRY}/php127/docker/nodejs:20-alpine .
            - docker push ${CNB_DOCKER_REGISTRY}/php127/docker/nodejs:20-alpine

        - name: 构建:nodejs18
          script:
            - cd ./nodejs/18
            - docker build -t ${CNB_DOCKER_REGISTRY}/php127/docker/nodejs:18-alpine .
            - docker push ${CNB_DOCKER_REGISTRY}/php127/docker/nodejs:18-alpine

        - name: 构建:nodejs16
          script:
            - cd ./nodejs/16
            - docker build -t ${CNB_DOCKER_REGISTRY}/php127/docker/nodejs:16-alpine .
            - docker push ${CNB_DOCKER_REGISTRY}/php127/docker/nodejs:16-alpine

        - name: 构建:php84-fpm
          script:
            - cd ./php/8.4/fpm-alpine
            - docker build -t php:8.4-fpm-alpine .
            - docker tag php:8.4-fpm-alpine ${CNB_DOCKER_REGISTRY}/php127/docker/php:8.4-fpm-alpine
            - docker push ${CNB_DOCKER_REGISTRY}/php127/docker/php:8.4-fpm-alpine

        - name: 构建:php84-fpm-nginx
          script:
            - cd ./php/8.4/fpm-alpine-nginx
            - docker build -t ${CNB_DOCKER_REGISTRY}/php127/docker/php:8.4-fpm-alpine-nginx .
            - docker push ${CNB_DOCKER_REGISTRY}/php127/docker/php:8.4-fpm-alpine-nginx

        - name: 构建:php84-cli
          script:
            - cd ./php/8.4/cli-alpine
            - docker build -t ${CNB_DOCKER_REGISTRY}/php127/docker/php:8.4-cli-alpine .
            - docker push ${CNB_DOCKER_REGISTRY}/php127/docker/php:8.4-cli-alpine

        - name: 构建:php74-fpm-nginx
          script:
            - cd ./php/7.4/fpm-alpine-nginx
            - docker build -t ${CNB_DOCKER_REGISTRY}/php127/docker/php:7.4.33-fpm-alpine-nginx .
            - docker push ${CNB_DOCKER_REGISTRY}/php127/docker/php:7.4.33-fpm-alpine-nginx

        - name: 构建:php74-fpm
          script:
            - cd ./php/7.4/fpm-alpine
            - docker build -t ${CNB_DOCKER_REGISTRY}/php127/docker/php:7.4.33-fpm-alpine .
            - docker push ${CNB_DOCKER_REGISTRY}/php127/docker/php:7.4.33-fpm-alpine

        - name: 构建:php74-cli
          script:
            - cd ./php/7.4/cli-alpine
            - docker build -t ${CNB_DOCKER_REGISTRY}/php127/docker/php:7.4.33-cli-alpine .
            - docker push ${CNB_DOCKER_REGISTRY}/php127/docker/php:7.4.33-cli-alpine

        - name: 构建:php74-cli-cron
          script:
            - cd ./php/7.4/cli-alpine/cron
            - docker build -t ${CNB_DOCKER_REGISTRY}/php127/docker/php:7.4.33-cli-alpine-cron .
            - docker push ${CNB_DOCKER_REGISTRY}/php127/docker/php:7.4.33-cli-alpine-cron

        - name: 构建:php74-cli-supervisord
          script:
            - cd ./php/7.4/cli-alpine/supervisord
            - docker build -t ${CNB_DOCKER_REGISTRY}/php127/docker/php:7.4.33-cli-alpine-supervisord .
            - docker push ${CNB_DOCKER_REGISTRY}/php127/docker/php:7.4.33-cli-alpine-supervisord

        - name: 构建:php73-fpm-nginx
          script:
            - cd ./php/7.3/fpm-alpine-nginx
            - docker build -t ${CNB_DOCKER_REGISTRY}/php127/docker/php:7.3.33-fpm-alpine-nginx .
            - docker push ${CNB_DOCKER_REGISTRY}/php127/docker/php:7.3.33-fpm-alpine-nginx

        - name: 构建:nginx
          script:
            - cd ./nginx
            - docker build -t ${CNB_DOCKER_REGISTRY}/php127/docker/nginx:1.26.2 .
            - docker push ${CNB_DOCKER_REGISTRY}/php127/docker/nginx:1.26.2

        - name: 构建:mysql57
          script:
            - cd ./mysql/5.7
            - docker build -t ${CNB_DOCKER_REGISTRY}/php127/docker/mysql:5.7.44 .
            - docker push ${CNB_DOCKER_REGISTRY}/php127/docker/mysql:5.7.44

        - name: 构建:redis625
          script:
            - cd ./redis/6.2.5
            - docker build -t ${CNB_DOCKER_REGISTRY}/php127/docker/redis:6.2.5 .
            - docker push ${CNB_DOCKER_REGISTRY}/php127/docker/redis:6.2.5

  web_trigger_nodejs:
    - services:
        - docker
      docker:
        image: cnbcool/default-build-env:latest
        volumes:
          - /root/
      stages:
        - name: docker login
          script:
            - docker login -u ${CNB_TOKEN_USER_NAME} -p "${CNB_TOKEN}" ${CNB_DOCKER_REGISTRY}

        - name: 构建:nodejs24
          script:
            - cd ./nodejs/24
            - docker build -t ${CNB_DOCKER_REGISTRY}/php127/docker/nodejs:24-alpine .
            - docker push ${CNB_DOCKER_REGISTRY}/php127/docker/nodejs:24-alpine

        - name: 构建:nodejs22
          script:
            - cd ./nodejs/22
            - docker build -t ${CNB_DOCKER_REGISTRY}/php127/docker/nodejs:22-alpine .
            - docker push ${CNB_DOCKER_REGISTRY}/php127/docker/nodejs:22-alpine

        - name: 构建:nodejs20
          script:
            - cd ./nodejs/20
            - docker build -t ${CNB_DOCKER_REGISTRY}/php127/docker/nodejs:20-alpine .
            - docker push ${CNB_DOCKER_REGISTRY}/php127/docker/nodejs:20-alpine

        - name: 构建:nodejs18
          script:
            - cd ./nodejs/18
            - docker build -t ${CNB_DOCKER_REGISTRY}/php127/docker/nodejs:18-alpine .
            - docker push ${CNB_DOCKER_REGISTRY}/php127/docker/nodejs:18-alpine

        - name: 构建:nodejs16
          script:
            - cd ./nodejs/16
            - docker build -t ${CNB_DOCKER_REGISTRY}/php127/docker/nodejs:16-alpine .
            - docker push ${CNB_DOCKER_REGISTRY}/php127/docker/nodejs:16-alpine

  web_trigger_php84:
    - services:
        - docker
      docker:
        image: cnbcool/default-build-env:latest
        volumes:
          - /root/
      stages:
        - name: docker login
          script:
            - docker login -u ${CNB_TOKEN_USER_NAME} -p "${CNB_TOKEN}" ${CNB_DOCKER_REGISTRY}

        - name: 构建:php84-fpm
          script:
            - cd ./php/8.4/fpm-alpine
            - docker build -t php:8.4-fpm-alpine .
            - docker tag php:8.4-fpm-alpine ${CNB_DOCKER_REGISTRY}/php127/docker/php:8.4-fpm-alpine
            - docker push ${CNB_DOCKER_REGISTRY}/php127/docker/php:8.4-fpm-alpine

        - name: 构建:php84-fpm-nginx
          script:
            - cd ./php/8.4/fpm-alpine-nginx
            - docker build -t ${CNB_DOCKER_REGISTRY}/php127/docker/php:8.4-fpm-alpine-nginx .
            - docker push ${CNB_DOCKER_REGISTRY}/php127/docker/php:8.4-fpm-alpine-nginx

        - name: 构建:php84-cli
          script:
            - cd ./php/8.4/cli-alpine
            - docker build -t ${CNB_DOCKER_REGISTRY}/php127/docker/php:8.4-cli-alpine .
            - docker push ${CNB_DOCKER_REGISTRY}/php127/docker/php:8.4-cli-alpine

  web_trigger_php74:
    - services:
        - docker
      docker:
        image: cnbcool/default-build-env:latest
        volumes:
          - /root/
      stages:
        - name: docker login
          script:
            - docker login -u ${CNB_TOKEN_USER_NAME} -p "${CNB_TOKEN}" ${CNB_DOCKER_REGISTRY}

        - name: 构建:php74-fpm-nginx
          script:
            - cd ./php/7.4/fpm-alpine-nginx
            - docker build -t ${CNB_DOCKER_REGISTRY}/php127/docker/php:7.4.33-fpm-alpine-nginx .
            - docker push ${CNB_DOCKER_REGISTRY}/php127/docker/php:7.4.33-fpm-alpine-nginx

        - name: 构建:php74-fpm
          script:
            - cd ./php/7.4/fpm-alpine
            - docker build -t ${CNB_DOCKER_REGISTRY}/php127/docker/php:7.4.33-fpm-alpine .
            - docker push ${CNB_DOCKER_REGISTRY}/php127/docker/php:7.4.33-fpm-alpine

        - name: 构建:php74-cli
          script:
            - cd ./php/7.4/cli-alpine
            - docker build -t ${CNB_DOCKER_REGISTRY}/php127/docker/php:7.4.33-cli-alpine .
            - docker push ${CNB_DOCKER_REGISTRY}/php127/docker/php:7.4.33-cli-alpine

        - name: 构建:php74-cli-cron
          script:
            - cd ./php/7.4/cli-alpine/cron
            - docker build -t ${CNB_DOCKER_REGISTRY}/php127/docker/php:7.4.33-cli-alpine-cron .
            - docker push ${CNB_DOCKER_REGISTRY}/php127/docker/php:7.4.33-cli-alpine-cron

        - name: 构建:php74-cli-supervisord
          script:
            - cd ./php/7.4/cli-alpine/supervisord
            - docker build -t ${CNB_DOCKER_REGISTRY}/php127/docker/php:7.4.33-cli-alpine-supervisord .
            - docker push ${CNB_DOCKER_REGISTRY}/php127/docker/php:7.4.33-cli-alpine-supervisord

  web_trigger_php73:
    - services:
        - docker
      docker:
        image: cnbcool/default-build-env:latest
        volumes:
          - /root/
      stages:
        - name: docker login
          script:
            - docker login -u ${CNB_TOKEN_USER_NAME} -p "${CNB_TOKEN}" ${CNB_DOCKER_REGISTRY}

        - name: 构建:php73-fpm-nginx
          script:
            - cd ./php/7.3/fpm-alpine-nginx
            - docker build -t ${CNB_DOCKER_REGISTRY}/php127/docker/php:7.3.33-fpm-alpine-nginx .
            - docker push ${CNB_DOCKER_REGISTRY}/php127/docker/php:7.3.33-fpm-alpine-nginx

  web_trigger_ide_all:
    - services:
        - docker
      docker:
        image: cnbcool/default-build-env:latest
        volumes:
          - /root/
      stages:
        - name: docker login
          script:
            - docker login -u ${CNB_TOKEN_USER_NAME} -p "${CNB_TOKEN}" ${CNB_DOCKER_REGISTRY}

        - name: 构建:ide-node24
          script:
            - cd ./ide/24
            - docker build -t ${CNB_DOCKER_REGISTRY}/php127/docker/ide:node24 .
            - docker push ${CNB_DOCKER_REGISTRY}/php127/docker/ide:node24

        - name: 构建:ide-node22
          script:
            - cd ./ide/22
            - docker build -t ${CNB_DOCKER_REGISTRY}/php127/docker/ide:node22 .
            - docker push ${CNB_DOCKER_REGISTRY}/php127/docker/ide:node22

        - name: 构建:ide-node20
          script:
            - cd ./ide/20
            - docker build -t ${CNB_DOCKER_REGISTRY}/php127/docker/ide:node20 .
            - docker push ${CNB_DOCKER_REGISTRY}/php127/docker/ide:node20

        - name: 构建:ide-node18
          script:
            - cd ./ide/18
            - docker build -t ${CNB_DOCKER_REGISTRY}/php127/docker/ide:node18 .
            - docker push ${CNB_DOCKER_REGISTRY}/php127/docker/ide:node18

        - name: 构建:ide-node16
          script:
            - cd ./ide/16
            - docker build -t ${CNB_DOCKER_REGISTRY}/php127/docker/ide:node16 .
            - docker push ${CNB_DOCKER_REGISTRY}/php127/docker/ide:node16

  web_trigger_ide_node24:
    - services:
        - docker
      docker:
        image: cnbcool/default-build-env:latest
        volumes:
          - /root/
      stages:
        - name: docker login
          script:
            - docker login -u ${CNB_TOKEN_USER_NAME} -p "${CNB_TOKEN}" ${CNB_DOCKER_REGISTRY}

        - name: 构建:ide-node24
          script:
            - cd ./ide/24
            - docker build -t ${CNB_DOCKER_REGISTRY}/php127/docker/ide:node24 .
            - docker push ${CNB_DOCKER_REGISTRY}/php127/docker/ide:node24

  web_trigger_ide_node22:
    - services:
        - docker
      docker:
        image: cnbcool/default-build-env:latest
        volumes:
          - /root/
      stages:
        - name: docker login
          script:
            - docker login -u ${CNB_TOKEN_USER_NAME} -p "${CNB_TOKEN}" ${CNB_DOCKER_REGISTRY}

        - name: 构建:ide-node22
          script:
            - cd ./ide/22
            - docker build -t ${CNB_DOCKER_REGISTRY}/php127/docker/ide:node22 .
            - docker push ${CNB_DOCKER_REGISTRY}/php127/docker/ide:node22

  web_trigger_ide_node20:
    - services:
        - docker
      docker:
        image: cnbcool/default-build-env:latest
        volumes:
          - /root/
      stages:
        - name: docker login
          script:
            - docker login -u ${CNB_TOKEN_USER_NAME} -p "${CNB_TOKEN}" ${CNB_DOCKER_REGISTRY}

        - name: 构建:ide-node20
          script:
            - cd ./ide/20
            - docker build -t ${CNB_DOCKER_REGISTRY}/php127/docker/ide:node20 .
            - docker push ${CNB_DOCKER_REGISTRY}/php127/docker/ide:node20

  web_trigger_ide_node18:
    - services:
        - docker
      docker:
        image: cnbcool/default-build-env:latest
        volumes:
          - /root/
      stages:
        - name: docker login
          script:
            - docker login -u ${CNB_TOKEN_USER_NAME} -p "${CNB_TOKEN}" ${CNB_DOCKER_REGISTRY}

        - name: 构建:ide-node18
          script:
            - cd ./ide/18
            - docker build -t ${CNB_DOCKER_REGISTRY}/php127/docker/ide:node18 .
            - docker push ${CNB_DOCKER_REGISTRY}/php127/docker/ide:node18

  web_trigger_ide_node16:
    - services:
        - docker
      docker:
        image: cnbcool/default-build-env:latest
        volumes:
          - /root/
      stages:
        - name: docker login
          script:
            - docker login -u ${CNB_TOKEN_USER_NAME} -p "${CNB_TOKEN}" ${CNB_DOCKER_REGISTRY}

        - name: 构建:ide-node16
          script:
            - cd ./ide/16
            - docker build -t ${CNB_DOCKER_REGISTRY}/php127/docker/ide:node16 .
            - docker push ${CNB_DOCKER_REGISTRY}/php127/docker/ide:node16

  web_trigger_nginx:
    - services:
        - docker
      docker:
        image: cnbcool/default-build-env:latest
        volumes:
          - /root/
      stages:
        - name: docker login
          script:
            - docker login -u ${CNB_TOKEN_USER_NAME} -p "${CNB_TOKEN}" ${CNB_DOCKER_REGISTRY}

        - name: 构建:nginx
          script:
            - cd ./nginx
            - docker build -t ${CNB_DOCKER_REGISTRY}/php127/docker/nginx:1.26.2 .
            - docker push ${CNB_DOCKER_REGISTRY}/php127/docker/nginx:1.26.2

  web_trigger_mysql:
    - services:
        - docker
      docker:
        image: cnbcool/default-build-env:latest
        volumes:
          - /root/
      stages:
        - name: docker login
          script:
            - docker login -u ${CNB_TOKEN_USER_NAME} -p "${CNB_TOKEN}" ${CNB_DOCKER_REGISTRY}

        - name: 构建:mysql57
          script:
            - cd ./mysql/5.7
            - docker build -t ${CNB_DOCKER_REGISTRY}/php127/docker/mysql:5.7.44 .
            - docker push ${CNB_DOCKER_REGISTRY}/php127/docker/mysql:5.7.44

  web_trigger_redis:
    - services:
        - docker
      docker:
        image: cnbcool/default-build-env:latest
        volumes:
          - /root/
      stages:
        - name: docker login
          script:
            - docker login -u ${CNB_TOKEN_USER_NAME} -p "${CNB_TOKEN}" ${CNB_DOCKER_REGISTRY}

        - name: 构建:redis625
          script:
            - cd ./redis/6.2.5
            - docker build -t ${CNB_DOCKER_REGISTRY}/php127/docker/redis:6.2.5 .
            - docker push ${CNB_DOCKER_REGISTRY}/php127/docker/redis:6.2.5

  web_trigger_lnmp:
    - services:
        - docker
      docker:
        image: cnbcool/default-build-env:latest
        volumes:
          - /root/
      stages:
        - name: docker login
          script:
            - docker login -u ${CNB_TOKEN_USER_NAME} -p "${CNB_TOKEN}" ${CNB_DOCKER_REGISTRY}

        - name: 构建:nginx
          script:
            - cd ./nginx
            - docker build -t ${CNB_DOCKER_REGISTRY}/php127/docker/nginx:1.26.2 .
            - docker push ${CNB_DOCKER_REGISTRY}/php127/docker/nginx:1.26.2

        - name: 构建:mysql57
          script:
            - cd ./mysql/5.7
            - docker build -t ${CNB_DOCKER_REGISTRY}/php127/docker/mysql:5.7.44 .
            - docker push ${CNB_DOCKER_REGISTRY}/php127/docker/mysql:5.7.44

        - name: 构建:redis625
          script:
            - cd ./redis/6.2.5
            - docker build -t ${CNB_DOCKER_REGISTRY}/php127/docker/redis:6.2.5 .
            - docker push ${CNB_DOCKER_REGISTRY}/php127/docker/redis:6.2.5
