concurrent = 1
check_interval = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "dfbb05ae12f4"
  url = "http://gitlab.test.com/"
  token = "GSmZXjZbw6HdgCwYF1PQ"
  executor = "docker"
  [runners.custom_build_dir]
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.docker]
    tls_verify = false
    image = "2.6"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    shm_size = 0

[[runners]]
  name = "dfbb05ae12f4"
  url = "http://gitlab.test.com"
  token = "5mXJk-Sv8mx1z-MNM7YK"
  executor = "shell"
  [runners.custom_build_dir]
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]

[[runners]]
  name = "dfbb05ae12f4"
  url = "http://gitlab.test.com"
  token = "zgr4rgoJTCxYfSrAzAHq"
  executor = "docker-ssh"
  [runners.custom_build_dir]
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.ssh]
    user = "root"
  [runners.docker]
    tls_verify = false
    image = "2.6"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    shm_size = 0

[[runners]]
  name = "dfbb05ae12f4"
  url = "http://gitlab.test.com"
  token = "3yUkUQSW-E9EjBLwxnyA"
  executor = "shell"
  [runners.custom_build_dir]
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
